name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: 📦 Install dependencies
        run: yarn
      - name: 🔣 Lint
        run: yarn types && yarn lint
      - name: 🧪 Unit test
        run: yarn test
      - name: 🚀 Deploy to Dev
        run: yarn deploy:dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
